apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
spec:
  ports:
  - port: 9092
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  ports:
  - port: 9092
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka-broker
  replicas: 3
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: broker
        image: akshaycgnlxdevops/custom-kafka:2.7
        env:
        - name: HOSTNAME_VALUE
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KAFKA_LISTENERS_COMMAND
          value: "echo \"PLAINTEXT://${HOSTNAME}.kafka-broker.default.svc.cluster.local:9092\""
        - name: KAFKA_LOG4J_OPTS
          value: "-Dlog4j.configuration=file:/opt/kafka/config/log4j.properties"
        - name: BROKER_ID_COMMAND
          value: "echo ${HOSTNAME##*-}"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zk-0.zk-hs.default.svc.cluster.local:2181"
        - name: KAFKA_LOG_DIRS
          value: "/var/lib/kafka/data/topics"
        - name: KAFKA_LOG_RETENTION_HOURS
          value: "-1"
        - name: KAFAK_ZOOKEEPER_CONNECTION_TIMEOUT_MS
          value: "6000"
        - name: KAFAK_AUTO_CREATE_TOPICS_ENABLE
          value: "false"
        ports:
        - containerPort: 9092
        livenessProbe:
          initialDelaySeconds: 60
          exec:
            command:
            - /bin/sh
            - -c
            - 'netstat -tulpn | grep LISTEN | grep 9092'
        volumeMounts:
        - name: data
          mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Mi
