kind: Service
apiVersion: v1
metadata:
  name: kafka-manager
spec:
  type: NodePort
  selector:
    app: kafka-manager
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-manager
  template:
    metadata:
      labels:
        app: kafka-manager
    spec:
      containers:
      - name: kafka-manager
        image: akshaycgnlxdevops/custom-kafka-manager:3.0.0.5
        ports:
        - containerPort: 9000
        env:
        - name: ZK_HOSTS
          value: "zk-0.zk-hs.default.svc.cluster.local:2181"
